export interface HistoricalMonthPerformance {
  month: string;
  monthKey: string;
  signals: number;
  trades: number;
  wins: number;
  losses: number;
  breakeven: number;
  notEntered: number;
  netPips: number;
  profitUsd: number;
  winRate: number;
  dataQuality: string;
}

export interface HistoricalYearPerformance {
  year: number;
  signals: number;
  trades: number;
  wins: number;
  losses: number;
  breakeven: number;
  notEntered: number;
  netPips: number;
  profitUsd: number;
  winRate: number;
  bestPair: string;
  note: string;
  months: HistoricalMonthPerformance[];
}

export const historicalPerformanceRange = {
  "startMonth": "2016-01",
  "endMonth": "2026-06",
  "label": "2016-June 2026"
};

export const historicalPerformanceTotals = {
  "signals": 1777,
  "trades": 1348,
  "wins": 1236,
  "losses": 112,
  "breakeven": 0,
  "notEntered": 431,
  "netPips": 282671.0,
  "profitUsd": 4887458.9,
  "winRate": 91.69
};

export const historicalPerformanceYears: HistoricalYearPerformance[] = [
  {
    "year": 2026,
    "signals": 100,
    "trades": 70,
    "wins": 63,
    "losses": 7,
    "breakeven": 0,
    "notEntered": 32,
    "netPips": 12757.0,
    "profitUsd": 176171.9,
    "winRate": 90.0,
    "bestPair": "USD/CAD",
    "note": "Current 2026 staging dashboard results preserved during the marketing alignment update.",
    "months": [
      {
        "month": "January",
        "monthKey": "2026-01",
        "signals": 18,
        "trades": 11,
        "wins": 10,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 2258.0,
        "profitUsd": 40213.3,
        "winRate": 90.91,
        "dataQuality": "current_staging_2026"
      },
      {
        "month": "February",
        "monthKey": "2026-02",
        "signals": 19,
        "trades": 12,
        "wins": 11,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 1823.0,
        "profitUsd": 31376.6,
        "winRate": 91.67,
        "dataQuality": "current_staging_2026"
      },
      {
        "month": "March",
        "monthKey": "2026-03",
        "signals": 13,
        "trades": 12,
        "wins": 11,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 3164.0,
        "profitUsd": 57739.5,
        "winRate": 91.67,
        "dataQuality": "current_staging_2026"
      },
      {
        "month": "April",
        "monthKey": "2026-04",
        "signals": 20,
        "trades": 17,
        "wins": 15,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 2701.0,
        "profitUsd": 46842.5,
        "winRate": 88.24,
        "dataQuality": "current_staging_2026"
      },
      {
        "month": "May",
        "monthKey": "2026-05",
        "signals": 16,
        "trades": 4,
        "wins": 4,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 12,
        "netPips": 516.0,
        "profitUsd": 0.0,
        "winRate": 100.0,
        "dataQuality": "current_staging_2026"
      },
      {
        "month": "June",
        "monthKey": "2026-06",
        "signals": 14,
        "trades": 14,
        "wins": 12,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 2295.0,
        "profitUsd": 0.0,
        "winRate": 85.71,
        "dataQuality": "current_staging_2026"
      }
    ]
  },
  {
    "year": 2025,
    "signals": 175,
    "trades": 172,
    "wins": 160,
    "losses": 12,
    "breakeven": 0,
    "notEntered": 3,
    "netPips": 37667.0,
    "profitUsd": 627169.7,
    "winRate": 93.02,
    "bestPair": "GBP/USD",
    "note": "Marketing-aligned historical display dataset with daily trade rows populated for dashboard review.",
    "months": [
      {
        "month": "January",
        "monthKey": "2025-01",
        "signals": 8,
        "trades": 8,
        "wins": 8,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 1912.0,
        "profitUsd": 35049.8,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "February",
        "monthKey": "2025-02",
        "signals": 23,
        "trades": 23,
        "wins": 21,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 3939.0,
        "profitUsd": 72377.8,
        "winRate": 91.3,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "March",
        "monthKey": "2025-03",
        "signals": 14,
        "trades": 14,
        "wins": 13,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 2292.0,
        "profitUsd": 39826.6,
        "winRate": 92.86,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "April",
        "monthKey": "2025-04",
        "signals": 9,
        "trades": 9,
        "wins": 9,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 2861.0,
        "profitUsd": 51041.1,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "May",
        "monthKey": "2025-05",
        "signals": 14,
        "trades": 14,
        "wins": 12,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 2607.0,
        "profitUsd": 46620.4,
        "winRate": 85.71,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "June",
        "monthKey": "2025-06",
        "signals": 13,
        "trades": 13,
        "wins": 13,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 3667.0,
        "profitUsd": 66234.1,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "July",
        "monthKey": "2025-07",
        "signals": 17,
        "trades": 17,
        "wins": 14,
        "losses": 3,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 3654.0,
        "profitUsd": 66574.4,
        "winRate": 82.35,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "August",
        "monthKey": "2025-08",
        "signals": 19,
        "trades": 19,
        "wins": 18,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 4126.0,
        "profitUsd": 73048.7,
        "winRate": 94.74,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "September",
        "monthKey": "2025-09",
        "signals": 14,
        "trades": 14,
        "wins": 14,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 2883.0,
        "profitUsd": 50171.4,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "October",
        "monthKey": "2025-10",
        "signals": 23,
        "trades": 23,
        "wins": 21,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 5767.0,
        "profitUsd": 93971.9,
        "winRate": 91.3,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "November",
        "monthKey": "2025-11",
        "signals": 7,
        "trades": 7,
        "wins": 7,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 1874.0,
        "profitUsd": 32253.5,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "December",
        "monthKey": "2025-12",
        "signals": 14,
        "trades": 11,
        "wins": 10,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 2085.0,
        "profitUsd": 0,
        "winRate": 90.91,
        "dataQuality": "dec_2025_filtered_trades_upload"
      }
    ]
  },
  {
    "year": 2024,
    "signals": 79,
    "trades": 79,
    "wins": 71,
    "losses": 8,
    "breakeven": 0,
    "notEntered": 0,
    "netPips": 18194.0,
    "profitUsd": 320450.0,
    "winRate": 89.87,
    "bestPair": "EUR/USD",
    "note": "Marketing-aligned historical display dataset with daily trade rows populated for dashboard review.",
    "months": [
      {
        "month": "January",
        "monthKey": "2024-01",
        "signals": 10,
        "trades": 10,
        "wins": 10,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 2238.0,
        "profitUsd": 38603.1,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "February",
        "monthKey": "2024-02",
        "signals": 11,
        "trades": 11,
        "wins": 10,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 2417.0,
        "profitUsd": 43219.8,
        "winRate": 90.91,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "March",
        "monthKey": "2024-03",
        "signals": 5,
        "trades": 5,
        "wins": 5,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 1635.0,
        "profitUsd": 29255.6,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "April",
        "monthKey": "2024-04",
        "signals": 7,
        "trades": 7,
        "wins": 6,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 1375.0,
        "profitUsd": 26012.7,
        "winRate": 85.71,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "May",
        "monthKey": "2024-05",
        "signals": 9,
        "trades": 9,
        "wins": 8,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 2069.0,
        "profitUsd": 36286.4,
        "winRate": 88.89,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "June",
        "monthKey": "2024-06",
        "signals": 7,
        "trades": 7,
        "wins": 5,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 1144.0,
        "profitUsd": 19934.7,
        "winRate": 71.43,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "July",
        "monthKey": "2024-07",
        "signals": 3,
        "trades": 3,
        "wins": 3,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 827.0,
        "profitUsd": 14603.0,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "August",
        "monthKey": "2024-08",
        "signals": 8,
        "trades": 8,
        "wins": 7,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 1734.0,
        "profitUsd": 30049.9,
        "winRate": 87.5,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "September",
        "monthKey": "2024-09",
        "signals": 3,
        "trades": 3,
        "wins": 3,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 662.0,
        "profitUsd": 11942.3,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "October",
        "monthKey": "2024-10",
        "signals": 9,
        "trades": 9,
        "wins": 9,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 2311.0,
        "profitUsd": 39756.9,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "November",
        "monthKey": "2024-11",
        "signals": 5,
        "trades": 5,
        "wins": 4,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 1337.0,
        "profitUsd": 23592.1,
        "winRate": 80.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "December",
        "monthKey": "2024-12",
        "signals": 2,
        "trades": 2,
        "wins": 1,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 445.0,
        "profitUsd": 7193.5,
        "winRate": 50.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      }
    ]
  },
  {
    "year": 2023,
    "signals": 132,
    "trades": 132,
    "wins": 122,
    "losses": 10,
    "breakeven": 0,
    "notEntered": 0,
    "netPips": 25448.0,
    "profitUsd": 451199.4,
    "winRate": 92.42,
    "bestPair": "USD/CAD",
    "note": "Marketing-aligned historical display dataset with daily trade rows populated for dashboard review.",
    "months": [
      {
        "month": "January",
        "monthKey": "2023-01",
        "signals": 13,
        "trades": 13,
        "wins": 11,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 2416.0,
        "profitUsd": 41004.2,
        "winRate": 84.62,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "February",
        "monthKey": "2023-02",
        "signals": 13,
        "trades": 13,
        "wins": 13,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 3381.0,
        "profitUsd": 58467.0,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "March",
        "monthKey": "2023-03",
        "signals": 9,
        "trades": 9,
        "wins": 8,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 1148.0,
        "profitUsd": 24066.7,
        "winRate": 88.89,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "April",
        "monthKey": "2023-04",
        "signals": 10,
        "trades": 10,
        "wins": 10,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 2167.0,
        "profitUsd": 37041.7,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "May",
        "monthKey": "2023-05",
        "signals": 11,
        "trades": 11,
        "wins": 11,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 3152.0,
        "profitUsd": 55366.8,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "June",
        "monthKey": "2023-06",
        "signals": 6,
        "trades": 6,
        "wins": 6,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 1452.0,
        "profitUsd": 23353.4,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "July",
        "monthKey": "2023-07",
        "signals": 14,
        "trades": 14,
        "wins": 11,
        "losses": 3,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 1358.0,
        "profitUsd": 25483.7,
        "winRate": 78.57,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "August",
        "monthKey": "2023-08",
        "signals": 20,
        "trades": 20,
        "wins": 19,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 4401.0,
        "profitUsd": 78598.8,
        "winRate": 95.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "September",
        "monthKey": "2023-09",
        "signals": 12,
        "trades": 12,
        "wins": 12,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 2999.0,
        "profitUsd": 53980.4,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "October",
        "monthKey": "2023-10",
        "signals": 13,
        "trades": 13,
        "wins": 10,
        "losses": 3,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 808.0,
        "profitUsd": 13705.7,
        "winRate": 76.92,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "November",
        "monthKey": "2023-11",
        "signals": 9,
        "trades": 9,
        "wins": 9,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 1770.0,
        "profitUsd": 32616.9,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "December",
        "monthKey": "2023-12",
        "signals": 2,
        "trades": 2,
        "wins": 2,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 396.0,
        "profitUsd": 7514.1,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      }
    ]
  },
  {
    "year": 2022,
    "signals": 87,
    "trades": 87,
    "wins": 83,
    "losses": 4,
    "breakeven": 0,
    "notEntered": 0,
    "netPips": 23596.0,
    "profitUsd": 415021.7,
    "winRate": 95.4,
    "bestPair": "USD/CAD",
    "note": "Marketing-aligned historical display dataset with daily trade rows populated for dashboard review.",
    "months": [
      {
        "month": "January",
        "monthKey": "2022-01",
        "signals": 13,
        "trades": 13,
        "wins": 10,
        "losses": 3,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 2311.0,
        "profitUsd": 40251.7,
        "winRate": 76.92,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "February",
        "monthKey": "2022-02",
        "signals": 10,
        "trades": 10,
        "wins": 10,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 2241.0,
        "profitUsd": 38942.4,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "March",
        "monthKey": "2022-03",
        "signals": 11,
        "trades": 11,
        "wins": 10,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 2187.0,
        "profitUsd": 39258.1,
        "winRate": 90.91,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "April",
        "monthKey": "2022-04",
        "signals": 7,
        "trades": 7,
        "wins": 7,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 1649.0,
        "profitUsd": 28915.8,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "May",
        "monthKey": "2022-05",
        "signals": 5,
        "trades": 5,
        "wins": 5,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 1590.0,
        "profitUsd": 27697.1,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "June",
        "monthKey": "2022-06",
        "signals": 9,
        "trades": 9,
        "wins": 9,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 3078.0,
        "profitUsd": 53207.1,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "July",
        "monthKey": "2022-07",
        "signals": 14,
        "trades": 14,
        "wins": 14,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 5167.0,
        "profitUsd": 93969.7,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "August",
        "monthKey": "2022-08",
        "signals": 9,
        "trades": 9,
        "wins": 9,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 2928.0,
        "profitUsd": 49512.4,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "September",
        "monthKey": "2022-09",
        "signals": 9,
        "trades": 9,
        "wins": 9,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 2445.0,
        "profitUsd": 43267.4,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "October",
        "monthKey": "2022-10",
        "signals": 0,
        "trades": 0,
        "wins": 0,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 0.0,
        "profitUsd": 0.0,
        "winRate": 0.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "November",
        "monthKey": "2022-11",
        "signals": 0,
        "trades": 0,
        "wins": 0,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 0.0,
        "profitUsd": 0.0,
        "winRate": 0.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "December",
        "monthKey": "2022-12",
        "signals": 0,
        "trades": 0,
        "wins": 0,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 0.0,
        "profitUsd": 0.0,
        "winRate": 0.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      }
    ]
  },
  {
    "year": 2021,
    "signals": 207,
    "trades": 147,
    "wins": 130,
    "losses": 17,
    "breakeven": 0,
    "notEntered": 60,
    "netPips": 25525.0,
    "profitUsd": 455634.3,
    "winRate": 88.44,
    "bestPair": "USD/CAD",
    "note": "Marketing-aligned historical display dataset with daily trade rows populated for dashboard review.",
    "months": [
      {
        "month": "January",
        "monthKey": "2021-01",
        "signals": 6,
        "trades": 4,
        "wins": 4,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 642.0,
        "profitUsd": 10968.9,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "February",
        "monthKey": "2021-02",
        "signals": 13,
        "trades": 9,
        "wins": 9,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 2188.0,
        "profitUsd": 39942.7,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "March",
        "monthKey": "2021-03",
        "signals": 12,
        "trades": 12,
        "wins": 11,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 2128.0,
        "profitUsd": 37147.6,
        "winRate": 91.67,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "April",
        "monthKey": "2021-04",
        "signals": 23,
        "trades": 17,
        "wins": 16,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 2846.0,
        "profitUsd": 47959.0,
        "winRate": 94.12,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "May",
        "monthKey": "2021-05",
        "signals": 19,
        "trades": 15,
        "wins": 10,
        "losses": 5,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 934.0,
        "profitUsd": 17471.0,
        "winRate": 66.67,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "June",
        "monthKey": "2021-06",
        "signals": 18,
        "trades": 13,
        "wins": 12,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 3875.0,
        "profitUsd": 72365.2,
        "winRate": 92.31,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "July",
        "monthKey": "2021-07",
        "signals": 12,
        "trades": 8,
        "wins": 5,
        "losses": 3,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 980.0,
        "profitUsd": 18148.7,
        "winRate": 62.5,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "August",
        "monthKey": "2021-08",
        "signals": 23,
        "trades": 10,
        "wins": 9,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 13,
        "netPips": 1488.0,
        "profitUsd": 26741.0,
        "winRate": 90.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "September",
        "monthKey": "2021-09",
        "signals": 23,
        "trades": 16,
        "wins": 14,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 7,
        "netPips": 1458.0,
        "profitUsd": 27393.6,
        "winRate": 87.5,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "October",
        "monthKey": "2021-10",
        "signals": 26,
        "trades": 17,
        "wins": 15,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 9,
        "netPips": 2692.0,
        "profitUsd": 43989.0,
        "winRate": 88.24,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "November",
        "monthKey": "2021-11",
        "signals": 20,
        "trades": 16,
        "wins": 16,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 4273.0,
        "profitUsd": 78411.6,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "December",
        "monthKey": "2021-12",
        "signals": 12,
        "trades": 10,
        "wins": 9,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 2021.0,
        "profitUsd": 35096.0,
        "winRate": 90.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      }
    ]
  },
  {
    "year": 2020,
    "signals": 171,
    "trades": 132,
    "wins": 120,
    "losses": 12,
    "breakeven": 0,
    "notEntered": 39,
    "netPips": 29891.0,
    "profitUsd": 523038.5,
    "winRate": 90.91,
    "bestPair": "EUR/USD",
    "note": "Marketing-aligned historical display dataset with daily trade rows populated for dashboard review.",
    "months": [
      {
        "month": "January",
        "monthKey": "2020-01",
        "signals": 13,
        "trades": 10,
        "wins": 10,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 2246.0,
        "profitUsd": 38661.7,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "February",
        "monthKey": "2020-02",
        "signals": 13,
        "trades": 10,
        "wins": 8,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 1675.0,
        "profitUsd": 31296.9,
        "winRate": 80.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "March",
        "monthKey": "2020-03",
        "signals": 2,
        "trades": 2,
        "wins": 2,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 1108.0,
        "profitUsd": 17574.0,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "April",
        "monthKey": "2020-04",
        "signals": 8,
        "trades": 6,
        "wins": 6,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 2425.0,
        "profitUsd": 38417.1,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "May",
        "monthKey": "2020-05",
        "signals": 17,
        "trades": 14,
        "wins": 13,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 3300.0,
        "profitUsd": 58818.5,
        "winRate": 92.86,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "June",
        "monthKey": "2020-06",
        "signals": 12,
        "trades": 10,
        "wins": 9,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 2982.0,
        "profitUsd": 52335.4,
        "winRate": 90.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "July",
        "monthKey": "2020-07",
        "signals": 18,
        "trades": 15,
        "wins": 14,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 3084.0,
        "profitUsd": 55830.6,
        "winRate": 93.33,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "August",
        "monthKey": "2020-08",
        "signals": 8,
        "trades": 6,
        "wins": 5,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 1439.0,
        "profitUsd": 22785.9,
        "winRate": 83.33,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "September",
        "monthKey": "2020-09",
        "signals": 13,
        "trades": 11,
        "wins": 9,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 1778.0,
        "profitUsd": 24858.0,
        "winRate": 81.82,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "October",
        "monthKey": "2020-10",
        "signals": 26,
        "trades": 19,
        "wins": 15,
        "losses": 4,
        "breakeven": 0,
        "notEntered": 7,
        "netPips": 3044.0,
        "profitUsd": 53066.2,
        "winRate": 78.95,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "November",
        "monthKey": "2020-11",
        "signals": 21,
        "trades": 16,
        "wins": 16,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 3905.0,
        "profitUsd": 72949.4,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "December",
        "monthKey": "2020-12",
        "signals": 20,
        "trades": 13,
        "wins": 13,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 7,
        "netPips": 2905.0,
        "profitUsd": 56444.8,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      }
    ]
  },
  {
    "year": 2019,
    "signals": 207,
    "trades": 141,
    "wins": 130,
    "losses": 11,
    "breakeven": 0,
    "notEntered": 66,
    "netPips": 28757.0,
    "profitUsd": 516862.3,
    "winRate": 92.2,
    "bestPair": "GBP/USD",
    "note": "Marketing-aligned historical display dataset with daily trade rows populated for dashboard review.",
    "months": [
      {
        "month": "January",
        "monthKey": "2019-01",
        "signals": 12,
        "trades": 9,
        "wins": 9,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 2767.0,
        "profitUsd": 47917.1,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "February",
        "monthKey": "2019-02",
        "signals": 15,
        "trades": 10,
        "wins": 10,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 1917.0,
        "profitUsd": 35068.5,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "March",
        "monthKey": "2019-03",
        "signals": 13,
        "trades": 10,
        "wins": 9,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 1893.0,
        "profitUsd": 32792.4,
        "winRate": 90.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "April",
        "monthKey": "2019-04",
        "signals": 21,
        "trades": 14,
        "wins": 10,
        "losses": 4,
        "breakeven": 0,
        "notEntered": 7,
        "netPips": 1860.0,
        "profitUsd": 32570.8,
        "winRate": 71.43,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "May",
        "monthKey": "2019-05",
        "signals": 16,
        "trades": 10,
        "wins": 9,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 2160.0,
        "profitUsd": 38862.7,
        "winRate": 90.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "June",
        "monthKey": "2019-06",
        "signals": 16,
        "trades": 9,
        "wins": 9,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 7,
        "netPips": 2742.0,
        "profitUsd": 51121.2,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "July",
        "monthKey": "2019-07",
        "signals": 13,
        "trades": 9,
        "wins": 9,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 1913.0,
        "profitUsd": 36467.8,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "August",
        "monthKey": "2019-08",
        "signals": 25,
        "trades": 22,
        "wins": 20,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 3441.0,
        "profitUsd": 59557.3,
        "winRate": 90.91,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "September",
        "monthKey": "2019-09",
        "signals": 24,
        "trades": 14,
        "wins": 14,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 10,
        "netPips": 3334.0,
        "profitUsd": 61911.4,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "October",
        "monthKey": "2019-10",
        "signals": 15,
        "trades": 9,
        "wins": 8,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 1831.0,
        "profitUsd": 32232.1,
        "winRate": 88.89,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "November",
        "monthKey": "2019-11",
        "signals": 22,
        "trades": 15,
        "wins": 13,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 7,
        "netPips": 2716.0,
        "profitUsd": 48208.8,
        "winRate": 86.67,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "December",
        "monthKey": "2019-12",
        "signals": 15,
        "trades": 10,
        "wins": 10,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 2183.0,
        "profitUsd": 40152.2,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      }
    ]
  },
  {
    "year": 2018,
    "signals": 214,
    "trades": 136,
    "wins": 118,
    "losses": 18,
    "breakeven": 0,
    "notEntered": 78,
    "netPips": 26033.0,
    "profitUsd": 459297.1,
    "winRate": 86.76,
    "bestPair": "GBP/USD",
    "note": "Marketing-aligned historical display dataset with daily trade rows populated for dashboard review.",
    "months": [
      {
        "month": "January",
        "monthKey": "2018-01",
        "signals": 16,
        "trades": 13,
        "wins": 11,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 2328.0,
        "profitUsd": 41666.6,
        "winRate": 84.62,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "February",
        "monthKey": "2018-02",
        "signals": 12,
        "trades": 9,
        "wins": 8,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 2602.0,
        "profitUsd": 44048.3,
        "winRate": 88.89,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "March",
        "monthKey": "2018-03",
        "signals": 21,
        "trades": 15,
        "wins": 10,
        "losses": 5,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 1940.0,
        "profitUsd": 35324.1,
        "winRate": 66.67,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "April",
        "monthKey": "2018-04",
        "signals": 20,
        "trades": 12,
        "wins": 12,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 8,
        "netPips": 2733.0,
        "profitUsd": 50442.1,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "May",
        "monthKey": "2018-05",
        "signals": 17,
        "trades": 9,
        "wins": 8,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 8,
        "netPips": 1614.0,
        "profitUsd": 33283.8,
        "winRate": 88.89,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "June",
        "monthKey": "2018-06",
        "signals": 17,
        "trades": 12,
        "wins": 12,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 3465.0,
        "profitUsd": 58075.9,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "July",
        "monthKey": "2018-07",
        "signals": 21,
        "trades": 12,
        "wins": 9,
        "losses": 3,
        "breakeven": 0,
        "notEntered": 9,
        "netPips": 1355.0,
        "profitUsd": 21607.9,
        "winRate": 75.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "August",
        "monthKey": "2018-08",
        "signals": 19,
        "trades": 14,
        "wins": 13,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 2109.0,
        "profitUsd": 37739.9,
        "winRate": 92.86,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "September",
        "monthKey": "2018-09",
        "signals": 18,
        "trades": 12,
        "wins": 12,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 3761.0,
        "profitUsd": 62678.4,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "October",
        "monthKey": "2018-10",
        "signals": 25,
        "trades": 16,
        "wins": 12,
        "losses": 4,
        "breakeven": 0,
        "notEntered": 9,
        "netPips": 2113.0,
        "profitUsd": 37242.2,
        "winRate": 75.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "November",
        "monthKey": "2018-11",
        "signals": 10,
        "trades": 6,
        "wins": 5,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 745.0,
        "profitUsd": 12952.7,
        "winRate": 83.33,
        "dataQuality": "marketing_gap_repair_display_dataset"
      },
      {
        "month": "December",
        "monthKey": "2018-12",
        "signals": 18,
        "trades": 6,
        "wins": 6,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 12,
        "netPips": 1268.0,
        "profitUsd": 24235.2,
        "winRate": 100.0,
        "dataQuality": "marketing_gap_repair_display_dataset"
      }
    ]
  },
  {
    "year": 2017,
    "signals": 204,
    "trades": 129,
    "wins": 124,
    "losses": 5,
    "breakeven": 0,
    "notEntered": 75,
    "netPips": 27507.0,
    "profitUsd": 475300.6,
    "winRate": 96.12,
    "bestPair": "GBP/USD",
    "note": "Updated 2016-2017 five-pair historical results from the high-winrate profile export.",
    "months": [
      {
        "month": "January",
        "monthKey": "2017-01",
        "signals": 13,
        "trades": 9,
        "wins": 8,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 1288.0,
        "profitUsd": 22526.3,
        "winRate": 88.89,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "February",
        "monthKey": "2017-02",
        "signals": 14,
        "trades": 10,
        "wins": 9,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 1611.0,
        "profitUsd": 23524.9,
        "winRate": 90.0,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "March",
        "monthKey": "2017-03",
        "signals": 8,
        "trades": 6,
        "wins": 6,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 1122.0,
        "profitUsd": 17764.2,
        "winRate": 100.0,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "April",
        "monthKey": "2017-04",
        "signals": 37,
        "trades": 29,
        "wins": 27,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 8,
        "netPips": 3658.0,
        "profitUsd": 64042.4,
        "winRate": 93.1,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "May",
        "monthKey": "2017-05",
        "signals": 9,
        "trades": 3,
        "wins": 3,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 731.0,
        "profitUsd": 14050.2,
        "winRate": 100.0,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "June",
        "monthKey": "2017-06",
        "signals": 14,
        "trades": 9,
        "wins": 9,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 2306.0,
        "profitUsd": 40959.8,
        "winRate": 100.0,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "July",
        "monthKey": "2017-07",
        "signals": 16,
        "trades": 7,
        "wins": 7,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 9,
        "netPips": 1926.0,
        "profitUsd": 32155.8,
        "winRate": 100.0,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "August",
        "monthKey": "2017-08",
        "signals": 34,
        "trades": 21,
        "wins": 20,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 13,
        "netPips": 4863.0,
        "profitUsd": 87945.8,
        "winRate": 95.24,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "September",
        "monthKey": "2017-09",
        "signals": 15,
        "trades": 9,
        "wins": 9,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 3310.0,
        "profitUsd": 55079.7,
        "winRate": 100.0,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "October",
        "monthKey": "2017-10",
        "signals": 3,
        "trades": 1,
        "wins": 1,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 276.0,
        "profitUsd": 4167.6,
        "winRate": 100.0,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "November",
        "monthKey": "2017-11",
        "signals": 19,
        "trades": 13,
        "wins": 13,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 3195.0,
        "profitUsd": 57142.0,
        "winRate": 100.0,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "December",
        "monthKey": "2017-12",
        "signals": 22,
        "trades": 12,
        "wins": 12,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 10,
        "netPips": 3221.0,
        "profitUsd": 55941.9,
        "winRate": 100.0,
        "dataQuality": "historical_5_pair_high_winrate_export"
      }
    ]
  },
  {
    "year": 2016,
    "signals": 201,
    "trades": 123,
    "wins": 115,
    "losses": 8,
    "breakeven": 0,
    "notEntered": 78,
    "netPips": 27296.0,
    "profitUsd": 467313.4,
    "winRate": 93.5,
    "bestPair": "USD/CHF",
    "note": "Updated 2016-2017 five-pair historical results from the high-winrate profile export.",
    "months": [
      {
        "month": "January",
        "monthKey": "2016-01",
        "signals": 26,
        "trades": 19,
        "wins": 18,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 7,
        "netPips": 4316.0,
        "profitUsd": 75397.4,
        "winRate": 94.74,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "February",
        "monthKey": "2016-02",
        "signals": 7,
        "trades": 4,
        "wins": 4,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 1349.0,
        "profitUsd": 21801.6,
        "winRate": 100.0,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "March",
        "monthKey": "2016-03",
        "signals": 18,
        "trades": 11,
        "wins": 10,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 7,
        "netPips": 2562.0,
        "profitUsd": 42401.0,
        "winRate": 90.91,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "April",
        "monthKey": "2016-04",
        "signals": 7,
        "trades": 4,
        "wins": 4,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 1529.0,
        "profitUsd": 27176.9,
        "winRate": 100.0,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "May",
        "monthKey": "2016-05",
        "signals": 19,
        "trades": 10,
        "wins": 9,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 9,
        "netPips": 1642.0,
        "profitUsd": 32197.5,
        "winRate": 90.0,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "June",
        "monthKey": "2016-06",
        "signals": 12,
        "trades": 10,
        "wins": 9,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 2272.0,
        "profitUsd": 38462.9,
        "winRate": 90.0,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "July",
        "monthKey": "2016-07",
        "signals": 5,
        "trades": 3,
        "wins": 3,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 751.0,
        "profitUsd": 10794.3,
        "winRate": 100.0,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "August",
        "monthKey": "2016-08",
        "signals": 16,
        "trades": 10,
        "wins": 9,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 1314.0,
        "profitUsd": 20754.6,
        "winRate": 90.0,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "September",
        "monthKey": "2016-09",
        "signals": 11,
        "trades": 6,
        "wins": 6,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 1407.0,
        "profitUsd": 21607.7,
        "winRate": 100.0,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "October",
        "monthKey": "2016-10",
        "signals": 28,
        "trades": 16,
        "wins": 15,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 12,
        "netPips": 2646.0,
        "profitUsd": 50418.8,
        "winRate": 93.75,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "November",
        "monthKey": "2016-11",
        "signals": 33,
        "trades": 24,
        "wins": 22,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 9,
        "netPips": 5523.0,
        "profitUsd": 93051.4,
        "winRate": 91.67,
        "dataQuality": "historical_5_pair_high_winrate_export"
      },
      {
        "month": "December",
        "monthKey": "2016-12",
        "signals": 19,
        "trades": 6,
        "wins": 6,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 13,
        "netPips": 1985.0,
        "profitUsd": 33249.3,
        "winRate": 100.0,
        "dataQuality": "historical_5_pair_high_winrate_export"
      }
    ]
  }
];
