export interface HistoricalMonthPerformance {
  month: string;
  monthKey: string;
  signals: number;
  trades: number;
  wins: number;
  losses: number;
  breakeven: number;
  notEntered: number;
  netPips: number;
  profitUsd: number;
  winRate: number;
  dataQuality: string;
}

export interface HistoricalYearPerformance {
  year: number;
  signals: number;
  trades: number;
  wins: number;
  losses: number;
  breakeven: number;
  notEntered: number;
  netPips: number;
  profitUsd: number;
  winRate: number;
  bestPair: string;
  note: string;
  months: HistoricalMonthPerformance[];
}

export const historicalPerformanceRange = {
  startMonth: "2018-01",
  endMonth: "2026-05",
  label: "2018-May 2026",
};

export const historicalPerformanceTotals = {
  signals: 1433,
  trades: 973,
  wins: 881,
  losses: 91,
  breakeven: 1,
  notEntered: 460,
  netPips: 163161,
  profitUsd: 2880998.1,
  winRate: 90.54,
};

export const historicalPerformanceYears: HistoricalYearPerformance[] = [
  {
    "year": 2026,
    "signals": 87,
    "trades": 54,
    "wins": 52,
    "losses": 2,
    "breakeven": 0,
    "notEntered": 33,
    "netPips": 9557,
    "profitUsd": 169247.6,
    "winRate": 96.3,
    "bestPair": "USD/CAD",
    "note": "Partial-year performance through May 2026 from the uploaded historical stats.",
    "months": [
      {
        "month": "January",
        "monthKey": "2026-01",
        "signals": 18,
        "trades": 12,
        "wins": 11,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 2274,
        "profitUsd": 39400.8,
        "winRate": 91.67,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "February",
        "monthKey": "2026-02",
        "signals": 19,
        "trades": 13,
        "wins": 12,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 1869,
        "profitUsd": 32195.4,
        "winRate": 92.31,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "March",
        "monthKey": "2026-03",
        "signals": 13,
        "trades": 10,
        "wins": 10,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 1961,
        "profitUsd": 36137.4,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "April",
        "monthKey": "2026-04",
        "signals": 20,
        "trades": 15,
        "wins": 15,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 2937,
        "profitUsd": 52351.4,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "May",
        "monthKey": "2026-05",
        "signals": 17,
        "trades": 4,
        "wins": 4,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 13,
        "netPips": 516,
        "profitUsd": 9162.6,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      }
    ]
  },
  {
    "year": 2025,
    "signals": 261,
    "trades": 190,
    "wins": 177,
    "losses": 12,
    "breakeven": 1,
    "notEntered": 71,
    "netPips": 35582,
    "profitUsd": 627781,
    "winRate": 93.16,
    "bestPair": "GBP/USD",
    "note": "Strong yearly run with broad participation across major pairs.",
    "months": [
      {
        "month": "January",
        "monthKey": "2025-01",
        "signals": 10,
        "trades": 7,
        "wins": 7,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 1592,
        "profitUsd": 28848.9,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "February",
        "monthKey": "2025-02",
        "signals": 27,
        "trades": 21,
        "wins": 20,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 4218,
        "profitUsd": 77009,
        "winRate": 95.24,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "March",
        "monthKey": "2025-03",
        "signals": 17,
        "trades": 11,
        "wins": 10,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 1429,
        "profitUsd": 25351.6,
        "winRate": 90.91,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "April",
        "monthKey": "2025-04",
        "signals": 13,
        "trades": 9,
        "wins": 9,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 2229,
        "profitUsd": 39207.3,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "May",
        "monthKey": "2025-05",
        "signals": 17,
        "trades": 14,
        "wins": 13,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 2742,
        "profitUsd": 49049.6,
        "winRate": 92.86,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "June",
        "monthKey": "2025-06",
        "signals": 22,
        "trades": 13,
        "wins": 13,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 9,
        "netPips": 3012,
        "profitUsd": 53800.9,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "July",
        "monthKey": "2025-07",
        "signals": 23,
        "trades": 16,
        "wins": 14,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 7,
        "netPips": 2548,
        "profitUsd": 45584,
        "winRate": 87.5,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "August",
        "monthKey": "2025-08",
        "signals": 22,
        "trades": 18,
        "wins": 17,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 3113,
        "profitUsd": 54691.5,
        "winRate": 94.44,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "September",
        "monthKey": "2025-09",
        "signals": 23,
        "trades": 16,
        "wins": 15,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 7,
        "netPips": 2624,
        "profitUsd": 45077.8,
        "winRate": 93.75,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "October",
        "monthKey": "2025-10",
        "signals": 30,
        "trades": 23,
        "wins": 20,
        "losses": 3,
        "breakeven": 0,
        "notEntered": 7,
        "netPips": 4023,
        "profitUsd": 67837.3,
        "winRate": 86.96,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "November",
        "monthKey": "2025-11",
        "signals": 22,
        "trades": 17,
        "wins": 16,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 4054,
        "profitUsd": 67667.8,
        "winRate": 94.12,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "December",
        "monthKey": "2025-12",
        "signals": 35,
        "trades": 25,
        "wins": 23,
        "losses": 1,
        "breakeven": 1,
        "notEntered": 10,
        "netPips": 3998,
        "profitUsd": 73655.3,
        "winRate": 92,
        "dataQuality": "exact_live_m15"
      }
    ]
  },
  {
    "year": 2024,
    "signals": 231,
    "trades": 138,
    "wins": 124,
    "losses": 14,
    "breakeven": 0,
    "notEntered": 93,
    "netPips": 18194,
    "profitUsd": 320447.9,
    "winRate": 89.86,
    "bestPair": "USD/CAD",
    "note": "Historical live-results period built from the uploaded performance dataset.",
    "months": [
      {
        "month": "January",
        "monthKey": "2024-01",
        "signals": 16,
        "trades": 13,
        "wins": 13,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 2517,
        "profitUsd": 43231.3,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "February",
        "monthKey": "2024-02",
        "signals": 18,
        "trades": 13,
        "wins": 10,
        "losses": 3,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 945,
        "profitUsd": 17617.7,
        "winRate": 76.92,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "March",
        "monthKey": "2024-03",
        "signals": 20,
        "trades": 8,
        "wins": 7,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 12,
        "netPips": 1044,
        "profitUsd": 18780.7,
        "winRate": 87.5,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "April",
        "monthKey": "2024-04",
        "signals": 18,
        "trades": 11,
        "wins": 10,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 7,
        "netPips": 1218,
        "profitUsd": 23386.5,
        "winRate": 90.91,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "May",
        "monthKey": "2024-05",
        "signals": 28,
        "trades": 17,
        "wins": 13,
        "losses": 4,
        "breakeven": 0,
        "notEntered": 11,
        "netPips": 1442,
        "profitUsd": 24487.7,
        "winRate": 76.47,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "June",
        "monthKey": "2024-06",
        "signals": 25,
        "trades": 14,
        "wins": 13,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 11,
        "netPips": 1622,
        "profitUsd": 28612.6,
        "winRate": 92.86,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "July",
        "monthKey": "2024-07",
        "signals": 20,
        "trades": 11,
        "wins": 9,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 9,
        "netPips": 562,
        "profitUsd": 8533.1,
        "winRate": 81.82,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "August",
        "monthKey": "2024-08",
        "signals": 21,
        "trades": 14,
        "wins": 14,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 7,
        "netPips": 2418,
        "profitUsd": 42810.6,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "September",
        "monthKey": "2024-09",
        "signals": 10,
        "trades": 4,
        "wins": 3,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 243,
        "profitUsd": 5198.1,
        "winRate": 75,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "October",
        "monthKey": "2024-10",
        "signals": 26,
        "trades": 14,
        "wins": 13,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 12,
        "netPips": 2452,
        "profitUsd": 43183.7,
        "winRate": 92.86,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "November",
        "monthKey": "2024-11",
        "signals": 13,
        "trades": 7,
        "wins": 7,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 1476,
        "profitUsd": 26579.6,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "December",
        "monthKey": "2024-12",
        "signals": 16,
        "trades": 12,
        "wins": 12,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 2255,
        "profitUsd": 38026.3,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      }
    ]
  },
  {
    "year": 2023,
    "signals": 193,
    "trades": 132,
    "wins": 122,
    "losses": 10,
    "breakeven": 0,
    "notEntered": 61,
    "netPips": 25448,
    "profitUsd": 444457.8,
    "winRate": 92.42,
    "bestPair": "GBP/USD",
    "note": "Strong yearly run with broad participation across major pairs.",
    "months": [
      {
        "month": "January",
        "monthKey": "2023-01",
        "signals": 18,
        "trades": 13,
        "wins": 11,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 2307,
        "profitUsd": 38493.4,
        "winRate": 84.62,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "February",
        "monthKey": "2023-02",
        "signals": 15,
        "trades": 13,
        "wins": 13,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 3336,
        "profitUsd": 57667.5,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "March",
        "monthKey": "2023-03",
        "signals": 9,
        "trades": 7,
        "wins": 7,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 1372,
        "profitUsd": 23187.8,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "April",
        "monthKey": "2023-04",
        "signals": 15,
        "trades": 9,
        "wins": 9,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 2110,
        "profitUsd": 36165.1,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "May",
        "monthKey": "2023-05",
        "signals": 20,
        "trades": 12,
        "wins": 12,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 8,
        "netPips": 3288,
        "profitUsd": 56800.4,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "June",
        "monthKey": "2023-06",
        "signals": 11,
        "trades": 6,
        "wins": 5,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 1083,
        "profitUsd": 16396.9,
        "winRate": 83.33,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "July",
        "monthKey": "2023-07",
        "signals": 18,
        "trades": 14,
        "wins": 11,
        "losses": 3,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 1528,
        "profitUsd": 27668.7,
        "winRate": 78.57,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "August",
        "monthKey": "2023-08",
        "signals": 26,
        "trades": 19,
        "wins": 18,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 7,
        "netPips": 4077,
        "profitUsd": 72592.9,
        "winRate": 94.74,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "September",
        "monthKey": "2023-09",
        "signals": 17,
        "trades": 12,
        "wins": 12,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 2781,
        "profitUsd": 49798.8,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "October",
        "monthKey": "2023-10",
        "signals": 19,
        "trades": 15,
        "wins": 12,
        "losses": 3,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 1333,
        "profitUsd": 24166.8,
        "winRate": 80,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "November",
        "monthKey": "2023-11",
        "signals": 16,
        "trades": 10,
        "wins": 10,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 1837,
        "profitUsd": 34005.4,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "December",
        "monthKey": "2023-12",
        "signals": 9,
        "trades": 2,
        "wins": 2,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 7,
        "netPips": 396,
        "profitUsd": 7514.1,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      }
    ]
  },
  {
    "year": 2022,
    "signals": 151,
    "trades": 109,
    "wins": 104,
    "losses": 5,
    "breakeven": 0,
    "notEntered": 42,
    "netPips": 23596,
    "profitUsd": 413381.3,
    "winRate": 95.41,
    "bestPair": "USD/CHF",
    "note": "High-conviction signal year with a strong entered-trade win rate.",
    "months": [
      {
        "month": "January",
        "monthKey": "2022-01",
        "signals": 22,
        "trades": 15,
        "wins": 14,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 7,
        "netPips": 2704,
        "profitUsd": 47681.3,
        "winRate": 93.33,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "February",
        "monthKey": "2022-02",
        "signals": 13,
        "trades": 11,
        "wins": 10,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 1612,
        "profitUsd": 26907.7,
        "winRate": 90.91,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "March",
        "monthKey": "2022-03",
        "signals": 12,
        "trades": 10,
        "wins": 9,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 1917,
        "profitUsd": 35156.1,
        "winRate": 90,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "April",
        "monthKey": "2022-04",
        "signals": 14,
        "trades": 9,
        "wins": 9,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 1737,
        "profitUsd": 30433,
        "winRate": 100,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "May",
        "monthKey": "2022-05",
        "signals": 7,
        "trades": 5,
        "wins": 5,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 1543,
        "profitUsd": 26963.9,
        "winRate": 100,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "June",
        "monthKey": "2022-06",
        "signals": 13,
        "trades": 9,
        "wins": 9,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 2777,
        "profitUsd": 47724.1,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "July",
        "monthKey": "2022-07",
        "signals": 17,
        "trades": 15,
        "wins": 14,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 3331,
        "profitUsd": 61616.4,
        "winRate": 93.33,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "August",
        "monthKey": "2022-08",
        "signals": 16,
        "trades": 10,
        "wins": 10,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 2952,
        "profitUsd": 49934,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "September",
        "monthKey": "2022-09",
        "signals": 14,
        "trades": 11,
        "wins": 11,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 2804,
        "profitUsd": 49718.2,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "October",
        "monthKey": "2022-10",
        "signals": 3,
        "trades": 3,
        "wins": 3,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 965,
        "profitUsd": 17614,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "November",
        "monthKey": "2022-11",
        "signals": 7,
        "trades": 4,
        "wins": 4,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 677,
        "profitUsd": 11250.6,
        "winRate": 100,
        "dataQuality": "exact_live_m15"
      },
      {
        "month": "December",
        "monthKey": "2022-12",
        "signals": 13,
        "trades": 7,
        "wins": 6,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 577,
        "profitUsd": 8382,
        "winRate": 85.71,
        "dataQuality": "exact_live_m15"
      }
    ]
  },
  {
    "year": 2021,
    "signals": 151,
    "trades": 105,
    "wins": 99,
    "losses": 6,
    "breakeven": 0,
    "notEntered": 46,
    "netPips": 18109,
    "profitUsd": 319810.5,
    "winRate": 94.29,
    "bestPair": "USD/CAD",
    "note": "High-conviction signal year with a strong entered-trade win rate.",
    "months": [
      {
        "month": "January",
        "monthKey": "2021-01",
        "signals": 6,
        "trades": 4,
        "wins": 3,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 317,
        "profitUsd": 5801.4,
        "winRate": 75,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "February",
        "monthKey": "2021-02",
        "signals": 9,
        "trades": 8,
        "wins": 7,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 1,
        "netPips": 1115,
        "profitUsd": 20699,
        "winRate": 87.5,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "March",
        "monthKey": "2021-03",
        "signals": 11,
        "trades": 6,
        "wins": 6,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 1421,
        "profitUsd": 25012.9,
        "winRate": 100,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "April",
        "monthKey": "2021-04",
        "signals": 16,
        "trades": 11,
        "wins": 11,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 1899,
        "profitUsd": 33769,
        "winRate": 100,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "May",
        "monthKey": "2021-05",
        "signals": 14,
        "trades": 10,
        "wins": 9,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 832,
        "profitUsd": 11883.3,
        "winRate": 90,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "June",
        "monthKey": "2021-06",
        "signals": 15,
        "trades": 9,
        "wins": 9,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 2848,
        "profitUsd": 53597.4,
        "winRate": 100,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "July",
        "monthKey": "2021-07",
        "signals": 13,
        "trades": 7,
        "wins": 5,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 839,
        "profitUsd": 12234.1,
        "winRate": 71.43,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "August",
        "monthKey": "2021-08",
        "signals": 12,
        "trades": 6,
        "wins": 5,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 590,
        "profitUsd": 10057.7,
        "winRate": 83.33,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "September",
        "monthKey": "2021-09",
        "signals": 10,
        "trades": 8,
        "wins": 8,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 1043,
        "profitUsd": 18706.4,
        "winRate": 100,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "October",
        "monthKey": "2021-10",
        "signals": 14,
        "trades": 13,
        "wins": 13,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 1,
        "netPips": 2155,
        "profitUsd": 38775.2,
        "winRate": 100,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "November",
        "monthKey": "2021-11",
        "signals": 20,
        "trades": 14,
        "wins": 14,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 3288,
        "profitUsd": 57209.4,
        "winRate": 100,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "December",
        "monthKey": "2021-12",
        "signals": 11,
        "trades": 9,
        "wins": 9,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 1762,
        "profitUsd": 32064.7,
        "winRate": 100,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      }
    ]
  },
  {
    "year": 2020,
    "signals": 95,
    "trades": 68,
    "wins": 56,
    "losses": 12,
    "breakeven": 0,
    "notEntered": 27,
    "netPips": 9580,
    "profitUsd": 169266.4,
    "winRate": 82.35,
    "bestPair": "EUR/USD",
    "note": "Historical live-results period built from the uploaded performance dataset.",
    "months": [
      {
        "month": "January",
        "monthKey": "2020-01",
        "signals": 7,
        "trades": 5,
        "wins": 5,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 1289,
        "profitUsd": 22786.2,
        "winRate": 100,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "February",
        "monthKey": "2020-02",
        "signals": 8,
        "trades": 6,
        "wins": 5,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 608,
        "profitUsd": 12443.8,
        "winRate": 83.33,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "March",
        "monthKey": "2020-03",
        "signals": 0,
        "trades": 0,
        "wins": 0,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": 0,
        "profitUsd": 0,
        "winRate": 0,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "April",
        "monthKey": "2020-04",
        "signals": 7,
        "trades": 5,
        "wins": 4,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 651,
        "profitUsd": 8892.2,
        "winRate": 80,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "May",
        "monthKey": "2020-05",
        "signals": 9,
        "trades": 9,
        "wins": 4,
        "losses": 5,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": -641,
        "profitUsd": -11492.7,
        "winRate": 44.44,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "June",
        "monthKey": "2020-06",
        "signals": 7,
        "trades": 4,
        "wins": 4,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 1953,
        "profitUsd": 35706.3,
        "winRate": 100,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "July",
        "monthKey": "2020-07",
        "signals": 8,
        "trades": 6,
        "wins": 6,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 1486,
        "profitUsd": 25970.9,
        "winRate": 100,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "August",
        "monthKey": "2020-08",
        "signals": 7,
        "trades": 5,
        "wins": 4,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 315,
        "profitUsd": 3941.8,
        "winRate": 80,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "September",
        "monthKey": "2020-09",
        "signals": 10,
        "trades": 6,
        "wins": 4,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 275,
        "profitUsd": 5153.3,
        "winRate": 66.67,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "October",
        "monthKey": "2020-10",
        "signals": 14,
        "trades": 10,
        "wins": 9,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 1171,
        "profitUsd": 21605,
        "winRate": 90,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "November",
        "monthKey": "2020-11",
        "signals": 9,
        "trades": 6,
        "wins": 5,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 838,
        "profitUsd": 14759.4,
        "winRate": 83.33,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "December",
        "monthKey": "2020-12",
        "signals": 9,
        "trades": 6,
        "wins": 6,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 1635,
        "profitUsd": 29500.2,
        "winRate": 100,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      }
    ]
  },
  {
    "year": 2019,
    "signals": 148,
    "trades": 103,
    "wins": 86,
    "losses": 17,
    "breakeven": 0,
    "notEntered": 45,
    "netPips": 13790,
    "profitUsd": 248502.2,
    "winRate": 83.5,
    "bestPair": "EUR/USD",
    "note": "Historical live-results period built from the uploaded performance dataset.",
    "months": [
      {
        "month": "January",
        "monthKey": "2019-01",
        "signals": 10,
        "trades": 7,
        "wins": 4,
        "losses": 3,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 645,
        "profitUsd": 12356,
        "winRate": 57.14,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "February",
        "monthKey": "2019-02",
        "signals": 9,
        "trades": 7,
        "wins": 6,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 2,
        "netPips": 1079,
        "profitUsd": 19824.5,
        "winRate": 85.71,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "March",
        "monthKey": "2019-03",
        "signals": 10,
        "trades": 6,
        "wins": 5,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 576,
        "profitUsd": 9817.8,
        "winRate": 83.33,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "April",
        "monthKey": "2019-04",
        "signals": 19,
        "trades": 12,
        "wins": 9,
        "losses": 3,
        "breakeven": 0,
        "notEntered": 7,
        "netPips": 1007,
        "profitUsd": 16928.1,
        "winRate": 75,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "May",
        "monthKey": "2019-05",
        "signals": 16,
        "trades": 10,
        "wins": 9,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 2140,
        "profitUsd": 38489.7,
        "winRate": 90,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "June",
        "monthKey": "2019-06",
        "signals": 7,
        "trades": 6,
        "wins": 3,
        "losses": 3,
        "breakeven": 0,
        "notEntered": 1,
        "netPips": 396,
        "profitUsd": 7607.9,
        "winRate": 50,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "July",
        "monthKey": "2019-07",
        "signals": 16,
        "trades": 11,
        "wins": 10,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 1112,
        "profitUsd": 20875.9,
        "winRate": 90.91,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "August",
        "monthKey": "2019-08",
        "signals": 12,
        "trades": 11,
        "wins": 11,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 1,
        "netPips": 2226,
        "profitUsd": 38244.5,
        "winRate": 100,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "September",
        "monthKey": "2019-09",
        "signals": 14,
        "trades": 10,
        "wins": 8,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 923,
        "profitUsd": 17501.5,
        "winRate": 80,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "October",
        "monthKey": "2019-10",
        "signals": 13,
        "trades": 8,
        "wins": 7,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 1601,
        "profitUsd": 28274.3,
        "winRate": 87.5,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "November",
        "monthKey": "2019-11",
        "signals": 15,
        "trades": 9,
        "wins": 8,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 6,
        "netPips": 1037,
        "profitUsd": 18816.4,
        "winRate": 88.89,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "December",
        "monthKey": "2019-12",
        "signals": 7,
        "trades": 6,
        "wins": 6,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 1,
        "netPips": 1048,
        "profitUsd": 19765.6,
        "winRate": 100,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      }
    ]
  },
  {
    "year": 2018,
    "signals": 116,
    "trades": 74,
    "wins": 61,
    "losses": 13,
    "breakeven": 0,
    "notEntered": 42,
    "netPips": 9305,
    "profitUsd": 168103.4,
    "winRate": 82.43,
    "bestPair": "AUD/USD",
    "note": "Historical live-results period built from the uploaded performance dataset.",
    "months": [
      {
        "month": "January",
        "monthKey": "2018-01",
        "signals": 5,
        "trades": 4,
        "wins": 3,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 1,
        "netPips": 487,
        "profitUsd": 10924.6,
        "winRate": 75,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "February",
        "monthKey": "2018-02",
        "signals": 2,
        "trades": 2,
        "wins": 1,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 0,
        "netPips": -252,
        "profitUsd": -4922.3,
        "winRate": 50,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "March",
        "monthKey": "2018-03",
        "signals": 12,
        "trades": 9,
        "wins": 7,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 1014,
        "profitUsd": 18715.8,
        "winRate": 77.78,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "April",
        "monthKey": "2018-04",
        "signals": 15,
        "trades": 7,
        "wins": 7,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 8,
        "netPips": 1535,
        "profitUsd": 28641.4,
        "winRate": 100,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "May",
        "monthKey": "2018-05",
        "signals": 7,
        "trades": 3,
        "wins": 2,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 276,
        "profitUsd": 4141.1,
        "winRate": 66.67,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "June",
        "monthKey": "2018-06",
        "signals": 10,
        "trades": 9,
        "wins": 8,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 1,
        "netPips": 2034,
        "profitUsd": 34903.4,
        "winRate": 88.89,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "July",
        "monthKey": "2018-07",
        "signals": 9,
        "trades": 5,
        "wins": 4,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 389,
        "profitUsd": 6435,
        "winRate": 80,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "August",
        "monthKey": "2018-08",
        "signals": 15,
        "trades": 11,
        "wins": 9,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 1100,
        "profitUsd": 19912.3,
        "winRate": 81.82,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "September",
        "monthKey": "2018-09",
        "signals": 11,
        "trades": 6,
        "wins": 5,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 790,
        "profitUsd": 14869.5,
        "winRate": 83.33,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "October",
        "monthKey": "2018-10",
        "signals": 11,
        "trades": 8,
        "wins": 8,
        "losses": 0,
        "breakeven": 0,
        "notEntered": 3,
        "netPips": 1447,
        "profitUsd": 25939.4,
        "winRate": 100,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "November",
        "monthKey": "2018-11",
        "signals": 9,
        "trades": 4,
        "wins": 3,
        "losses": 1,
        "breakeven": 0,
        "notEntered": 5,
        "netPips": 140,
        "profitUsd": 1742.1,
        "winRate": 75,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      },
      {
        "month": "December",
        "monthKey": "2018-12",
        "signals": 10,
        "trades": 6,
        "wins": 4,
        "losses": 2,
        "breakeven": 0,
        "notEntered": 4,
        "netPips": 345,
        "profitUsd": 6801.1,
        "winRate": 66.67,
        "dataQuality": "h1_fallback_no_complete_m15_cache"
      }
    ]
  }
];
