export const TermsAndCondition = [
  {
    section: [
      `<p>Welcome to the 1st FX!</p>
      <br/>
      <p>These terms and conditions, together with any documents that expressly incorporate by reference (collectively, referred to as <span>“Terms of Use” or “Terms”</span>), govern the access to and use of ________________________ (the <span>“Website”</span>) or ____________ mobile application (the <span>“App”</span>), including any content, functionality, and services provided, such as Forex education, AI-powered trading signals, and community engagement features (collectively, the "Services").</p>
        <br/>
      <p>By accessing or using the Website, you signify your acceptance of and agreement to comply with these Terms. The Website and its content are owned and operated by_________________, a _______________company bearing license ____________ and having its registered office at ______________, Costa Rica (the <span>“Company”</span>).</p>
      <br/>
      <p>These Terms constitute a binding agreement between you (the "User") and the Company, including its affiliates (collectively referred to as "we," "us," or "our"). The use of "you," "your," or "User" refers to any individual or entity accessing the Services provided through the Website.</p>
      `,
    ],
  },
  {
    section: [
      `<h3>ACCEPTANCE OF AGREEMENT</h3>`,
      `<br/>`,
      `<p>Please read the following terms carefully. By registering for, accessing, browsing, or using the website, you acknowledge that you have read, understood, and agree to be bound by the terms including any modifications that we make, whether you are a “Visitor” (simply browsing Website) or you are a “Member” (you have registered with Website). You also acknowledge and agree that you have read and understood <span>our Privacy Statement, found at _____________/privacy-policy, incorporated herein by reference.</span>, without any limitation or qualification.</p>
        <br/>
        <p>We may modify these Terms at any time without notice to you by posting revised Terms on our site. It is your responsibility to regularly check the Website to determine if there have been changes to these Terms and to review such changes. If You do not agree to these Terms, do not use the website. If, at any time, any part of the Terms is no longer acceptable to You, immediately terminate Your use of the website. Any terms and conditions proposed by you which are in addition to or which conflict with these terms and conditions of service are expressly rejected by the website and shall be of no force or effect.</p>
        <br/>
        <p>This Agreement also constitutes the entire and only agreement between us and you, and supersedes all prior or contemporaneous agreements, representations, warranties, and understandings with respect to the Website, the content, products, or services provided by or through the Website, and the subject matter of this Agreement.</p><br/>`,
    ],
  },
  {
    section: [
      `<h3>SERVICES</h3>`,
      `<br/>`,
      `<h3>Description of Our Services</h3>`,
      `<br/>`,
      `<p>We offer a diverse range of Services designed to empower our users with knowledge, tools, and a supportive community for Forex trading. Our website provides comprehensive online courses catering to all levels of expertise, from beginners to advanced traders. These courses include proprietary strategies to enhance trading skills and profitability. We Leverage AI-powered personalized learning methods to ensure that each user receives tailored educational content for optimized skill development. Our website also offers real-time trading signals generated by advanced algorithms and automated trading bots, along with charting tools and risk management features to navigate market fluctuations. Additionally, users can engage in interactive forums, live Q&A sessions, and mentorship opportunities, as well as participate in performance reviews and contribute as bloggers or mentors to enrich our community.</p><br/>`,
    ],
  },
  {
    section: [
      `<h3>Community Forum Policy</h3>`,
      `<br/>`,
      `<p>Use of the Website is also governed by our Forum Policy, which is incorporated into this Terms by this reference. The complete policy is located at______________.</p>`,
    ],
  },
  {
    section: [
      `<h3>Limitations to our Services</h3>`,
      `<br/>`,
      `<p>The services and education content on website are for your personal and non-commercial use, unless specifically endorsed or approved by Us. As a condition of your use of the Website, you will not use the Website for any purpose that is unlawful or prohibited by this Agreement. You may not use the Service to:</p>
        <br/>
        <ul>
        <li>Post or transmit any content that is disruptive, uncivil, abusive, vulgar, profane, obscene, hateful, fraudulent, threatening, harassing, defamatory, which discloses private or personal matters concerning any person, or in the sole judgment of Us, is objectionable or which restricts or inhibits any other person from using or enjoying the site, or which may expose Us or its users to any harm or liability of any type;</li>
        <li>Post or transmit any material that you don't have legal rights to transmit (such as copyrighted materials or trade secrets) or under contractual or fiduciary relationships (such as nondisclosure agreements);</li>
        <li>Post, transmit, or link to sexually explicit material;</li>
        <li>Impersonate any person, or falsely state or otherwise misrepresent your affiliation with a person or entity;</li>
        <li>Impersonate another member or person;</li>
        <li>Use the account, username, or password of another member at any time or provide your password to any third party or permitting any third party to access your account;</li>
        <li>Sell or otherwise transfer your profile;</li>
        <li> Use any information obtained from US in order to harass, abuse, or harm another person;</li>
        <li>Post or transmit any advertising, promotional materials, or other forms of solicitation, whether personal or commercial, including chain letters, pyramid schemes, and links or URLs to third party websites deemed as commercial;</li>
        <li>Violate any applicable law or regulation while accessing and using our sites, including, without limitation, the rules and regulations of Costa Rican regulators and the national or other securities exchanges (especially and including the rule against making false or misleading statements to manipulate the price of any security);</li>
        <li>Post or transmit any file that contains viruses, corrupted files, "Trojan Horses," or any other contaminating or harmful files that may damage or corrupt someone else's computer;</li>
        <li>Use any automated means, including without limitation, agents, robots, scripts, or spiders, to access, monitor, copy or harvest data from any part of our sites;</li>
        <li>Use any automated means, including without limitation, agents, robots, scripts, or spiders, to post content to any part of our website;</li>
        <li>Attempt to gain unauthorized access to services, materials, other accounts, computer systems or networks connected to any of our server or to the website, through hacking, password mining or any other means not intentionally made available through the Website;</li>
        <li>Take any action that imposes an unreasonably or disproportionately large load on our infrastructure or disrupts the functioning of our systems or Service; and</li>
        <li>Take any action that damages or disrupts the functioning of our systems or service.</li>
        </ul>
        <br/>
        <p>We may engage other companies to provide services for the Service, including hosting, the collection and processing of payments and the supply of components and features for the functionality of the Services. We may provide access to or make available additional third-party software or services. We do not make any representations or warranties, express or implied, regarding any third-party software or service. They are provided only as a convenience to you, and We do not endorse and is not affiliated with any third-party software or service. You agree that any use of third-party software or service is at risk and subject to the terms applicable to that third-party software or service.</p>
        <br/>
        <p>We reserve the right to investigate complaints or reported violations of this terms and to take any action we deem appropriate, including but not limited to reporting any suspected unlawful activity to law enforcement officials, regulators, or other third-parties and disclosing any information necessary or appropriate to such persons or entities relating to your account, email address, usage history, posted materials, IP addresses and traffic information.</p>
        <br/>`,
    ],
  },
  {
    section: [
      `<h3>Community Forum Policy</h3>`,
      `<br/>`,
      `<h3>Account Registration</h3>`,
      `<br/>`,
      `<p>To access full features of our Services, you are required to create an account by providing accurate and complete information, including but not limited to your name, email address, phone number, and physical address. This information will be held and used in accordance with our Privacy Policy and relevant notices / policies. We shall collect user data through signup form at the time of account creation, further details for the same can be updated by the user on the user or profile page of account. Additionally for verification purposes we may require you to authenticate your account with our service partners and have access to details for paid services. You must provide the correct details in all fields and keep the details updated including and not limited to your personal information like postal address, email address, telephone number(s) etc. Any discrepancy in the KYC or other mandatory requirements shall make you ineligible for services, unless and until the same is updated.</p>`,
      `<br/>`,
      `<p>It is your responsibility to ensure that this information is kept up to date. You are also responsible for safeguarding the confidentiality of your account login credentials, including your password, and for all activities that occur under your account. We recommend that you do not share your login information with anyone and promptly notify us if you suspect any unauthorized use of your account.</p>`,
      `<br/>`,
      `<p>Any information provided by you to us should be complete and truthful to the best of your knowledge. We are not obliged to cross-check or verify the information provided by you and we will not take any responsibility for any outcome or consequence as a result of you providing incorrect information or concealing any relevant information from us. In case if we feel to have some background checking, then we may, at any time, require you to provide us with additional documentation and proofs to verify the correctness of this information, failing which we reserve the right to hold / suspend or terminate your registration.</p>`,
      `<br/>`,
      `<div>
      <p>Your registration or account creation on website shall be subject to the following:</p>
      <ul>
      <li>You shall not register or operate more than one user account with us.</li>
      <li>You shall not create an account using a false identity or information, or on behalf of someone other than yourself;</li>
      <li>You shall not have an account or use the service if you have previously been removed by us or previously been banned from taking our services, and we at our sole discretion may allow You to create/reopen such account;</li>
      <li>You are responsible for any use of your credit card or other payment instrument;</li>
      <li>You agree to receive promotional messages relating to various tournaments & Bonus through short messaging services, electronic mails, push notifications and other means. If you wish to unsubscribe to the messaging services, please contact at the email id provided to you for unsubscribing.</li>
      </ul>
      </div>`,
    ],
  },
  {
    section: [
      `<h3>Eligibility</h3>`,
      `<br/>`,
      `<p>Our services are exclusively offered to and may be solely used by persons of or over the age of eighteen (18) years and residing in a jurisdiction where the access to or use of the Services is not restricted by the applicable law and the Terms. By purchasing or signing up for any service we offer, You warrant and represent to Us to be of or over the age of eighteen (18) years.</p>
        <br/>
        <p>We reserve the right to refuse, restrict, or terminate the provision of any and all services to You in the event You (i) are subject to the relevant International sanctions, (ii) have a criminal record related to financial crime, or(iii) are residing in a Prohibited Jurisdiction. You understand that there may be restrictions or laws in some jurisdictions that prohibit Your access to one or more of the Services, and You undertake sole responsibility for using such services in compliance with all such applicable laws of Your jurisdiction.</p>`,
    ],
  },
  {
    section: [
      `<h3>SUBSCRIPTION AND PAYMENT TERMS</h3>`,
      `<br/>`,
      `<p>We offer paid access to Premium content and features on websites, subject to these Subscription terms and conditions herein.</p>
        <br/>
        <p>The applicable Premium Service fee, Billing Cycle, and Renewal Date are available for review before purchasing and after purchasing by viewing your account’s Subscription page.  Our account holders who pay for Premium Service will be referred to as an “Authorized Subscriber” or “Subscriber”.  Premium Service is offered as a monthly subscription.  Subscribers must provide us with a current, valid, and accepted method of payment (also referred to as “Payment Method”) to purchase the Premium Service. “Billing” means a charge, debit, or other payment clearance, as applicable, against your Payment Method.</p>`,
    ],
  },
  {
    section: [
      `<h3>Payment Policy</h3>`,
      `<br/>`,
      `<p>We will bill the applicable Premium Service fee to your Payment Method at the beginning of the paying portion of your subscription and each month thereafter (also referred to as “Billing Cycle”) depending on your selected Billing Plan Type unless and until you cancel your membership.</p>
        <p>You agree to provide accurate, current, and complete information during the payment process. You represent and warrant that you are authorized to use such Payment Method for purchases, and you hereby authorize Us or its third-party payment processor to charge your Payment Method for any and all fees you incur in connection with your Subscription or use of the Subscription.</p>
        <br/>
        <p>Your Subscription includes enrollment in an automatically renewing payment plan. Payment will be charged to your chosen Payment Method at confirmation of purchase and in advance of each new Billing Cycle unless canceled.</p>
        <br/>
        <p>All fees and applicable taxes are payable in _______________. Subscription fees are fully earned by Us upon payment. Our Subscription are exclusive of all applicable taxes. If You are using our services as an Entrepreneur or a User, You shall be responsible for fulfilling all tax obligations related to using our services in accordance with the relevant laws of the jurisdiction applicable to You. We shall not be held liable for Your omission to fulfil the required tax obligations as per the applicable laws and the tax authorities of Your jurisdiction.</p>`,
    ],
  },
  {
    section: [
      `<h3>Payment Details</h3>`,
      `<br/>`,
      `<p>We will keep your payment information on file, but you are responsible for keeping this up to date in the Manage Subscription section of your Account.  If a payment is not successfully authorized due to expiration, insufficient funds, or otherwise, we will reattempt to authorize the payment at least 3 more times over a period of 15 days.</p>
      <br/>
      <p>We do reserve the right to suspend or terminate your Subscription if the payment authorization fails after multiple number of attempts.</p>
      <br/>
      <p>You agree to keep a current email address in your account settings in the event we need to contact you regarding payment issues.</p>`,
    ],
  },
  {
    section: [
      `<h3>Renewal Policy</h3>`,
      `<br/>`,
      `<p>We automatically bill your Payment Method each month or year on the calendar day corresponding to the commencement of your paying Subscription (also referred to as “Renewal Date”).</p>
        <br/>
        <p>We reserve the right to change the timing of our Billing, in particular as indicated below, if your Payment Method has not been successfully settled. In the event you’re paying Subscription begin on a day not contained in a given month, we may bill your Payment Method on a day in the applicable month or such other day as we deem appropriate.</p>
        <br/>
        <p>For monthly subscriptions, we will notify you of the pending renewal of your subscription 7 days prior to the date your subscription renews, except as otherwise required by law. For all subscriptions, you must cancel your subscription before it renews in order to avoid billing subscription fees for the renewal term to your preferred method of payment.</p>
        <br/>
        <p>Your Subscription will continue until you cancel. If you do nothing, we will charge the payment method you selected. While you may cancel at any time before your subscription ends by signing into your user account to manage your Subscription or by contacting us at ____________, <span>your payment is non-refundable, and your access will continue until the end of your subscription,</span> after which the cancellation will take full effect, and no further changes will be made.</p>`,
    ],
  },
  {
    section: [
      `<h3>Price Changes</h3>`,
      `<br/>`,
      `<p>We reserve the right to change our pricing at any time.  In the event of a price change, we will attempt to notify you in advance by sending an email to the email address on record for your account.  If you do not cancel your Subscription upon notice of a price change, the Subscription will be renewed at the start of the next Billing Cycle at the price in effect at that time. You agree to keep a current email address in your account settings.</p>
      <br/>
      <p>We may at our sole discretion, provide discount schemes, as offers for users of the website from time to time. We may offer an instant discount on the invoice or pre-agreed discount based on the schemes. The discount schemes may be called bonuses, cashbacks, promotional offers, discounts, etc. (“Schemes”) and details of the Schemes will be communicated to the users accessing the Website before availing the Schemes. The Schemes can be used by the Users, subject to such terms and conditions as may be prescribed. Such terms and conditions may include details of such Schemes, their validity for availability/ utilization, restriction in availability/ utilization when used in conjunction with other Schemes, discounts or vouchers, etc.</p>`,
    ],
  },
  {
    section: [
      `<h3>Cancellation Policy</h3>`,
      `<br/>`,
      `<p><span>You can cancel your Subscription at any time online by using your account</span> (go to your <span>Avatar | Preferences | Manage Subscription</span> option or by contacting customer support at _______________. Subscription cancellations will take effect at the end of the current Billing Cycle unless otherwise disclosed.</p>
      <br/>
      <p>When canceling a monthly subscription, all future charges associated with future months of your subscription will be canceled. You may notify us of your intent to cancel at any time online or by email; your cancellation will become effective at the end of your current monthly Billing Cycle. <span>You will not receive a refund for any partially used monthly Billing Cycle.</span>  However, your subscription access and/or delivery and accompanying subscriber benefits will continue for the remainder of the current monthly Billing Cycle, unless otherwise indicated.</p>
      <br/>
      <p>Canceling a monthly Subscription will not cancel or delete your user account or access to the website and free-tier content, features, and services.</p>
      <br/>
      <p>We may suspend or terminate your Premium Subscription if we are prevented from providing services to you, or accepting payment from you, by applicable law or circumstances beyond our control, or if we cease publishing Premium content. If we terminate for any of these reasons, we will provide you with a pro-rata refund to the extent permitted by applicable law.</p>
      <p>We may also suspend or terminate your Subscription, without refund, if you breach these Terms and Conditions, or in the event of any verbal or written abuse of any kind (including abusive, offensive or aggressive language) directed towards our Customer Support team, other personnel of ours, or any member of the public, with or without notice and without any further liability or obligation to you.</p>`,
    ],
  },
  {
    section: [
      `<h3>Third-Party Payment Processors</h3>`,
      `<br/>`,
      `<p>We may collect payments and/or fees through secure third-party payment processors, all of which accept payments through methods detailed on the applicable payment screen.  These include, but are not limited to, various credit cards, digital wallets, Stripe, Memberful, and PayPal. Such payment methods are subject to change. Credit cards and billing information that you supply to our payment processors are not stored by us and are subject to each of our third-party payment processors’ own private policies and terms and conditions. Third-party payment processors may charge a fee to process payments, and we are not responsible for such fees. We disclaim all liability with regard to any fees, claims or disputes, you may have with third-party payment processors.</p>`,
    ],
  },
  {
    section: [
      `<h3>DATA PROTECTION</h3>`,
      `<br/>`,
      `<h3>Data Processing</h3>`,
      `<br/>`,
      `<p>You agree and consent to our processing of Your personal data in accordance with the applicable data protection regulations, including but not limited to the EU General Data Protection Regulation ("GDPR") wherever, such regulations are applicable to You or Your data. You Data will processed as per our Privacy Policy.</p>`,
    ],
  },
  {
    section: [
      `<h3>Your Rights</h3>`,
      `<br/>`,
      `<p>You have certain rights regarding Your personal data, including the right to access, rectify, erase, or restrict the processing of Your data, as well as the right to object to the processing of Your data. You can exercise these rights by contacting Us or by referring to the instructions in our Privacy Policy. For more details, please review our Privacy Policy.</p>`,
    ],
  },
  {
    section: [
      `<h3>AI AND DATA USAGE</h3>`,
      `<br/>`,
      `<p>By using our Services, you acknowledge and agree that data generated during your use of the service provided us, including but not limited to interaction logs, trading patterns, and feedback, may be used for training and improving our AI systems. We ensure that such data will be anonymized and aggregated to the extent possible to protect your privacy. You have the right to opt out of this data usage by contacting us at the email provided below.</p>
      <br/>
      <p>We may anonymize and aggregate data generated during your use of our Services to train and improve our AI algorithms. This ensures that the data used for such purposes cannot be linked back to you as an individual. We do not use personally identifiable information (PII) for AI training without your explicit consent.</p>
      <br/>
      <p>You have the right to opt out of having your data used for AI training purposes. Please contact us at email provided end of the Terms to exercise this right. Opting out may affect your access to other features and functionalities of our Services. For more details, please refer our AI Policy at_____________.</p>`,
    ],
  },
  {
    section: [
      `<h3>INTELLECTUAL PROPERTY RIGHTS</h3>`,
      `<br/>`,
      `<p>We own, has licensed, or otherwise has rights to use all of the content that appears on the Website or in App including but not limited to proprietary strategies and AI algorithms. All rights, title and interest in and to the our offerings (including without limitation any course, titles, computer code, themes, objects, characters, character names, stories, dialogue, catch phrases, concepts, artwork, animations, sounds, musical compositions, audio-visual effects, methods of operation, moral rights, documentation, in-chat transcripts, character profile information, recordings of trade using our service) are owned / licensed by Company. Company reserves all rights, including without limitation, all intellectual property rights or other proprietary rights, in connection with its Content and the service. All Content with the exception of third-party content is owned by Company.</p>`,
    ],
  },
  {
    section: [
      `<h3>Trademarks and Logos</h3>`,
      `<br/>`,
      `<p>All trademarks, logos, and trade names displayed on the Website belong to the Us and You shall not be authorized to use the same without obtaining our permission.</p>
        <br/>
        <p>You are granted a limited, non-exclusive, and non-transferable license to use the materials for personal and educational purposes only. This license does not permit any reproduction, distribution, or modification of our content under any circumstance. </p>
        <br/>
        <p>Notwithstanding anything to the contrary herein, you shall have no ownership or other property interest in the account, and you further acknowledge and agree that all rights in and to the account (except for any personal information therein) are and shall forever be owned by Company. You agree that you have no right or title in or to any content that appears in our service, including without limitation the virtual trades or currency appearing or originating in any virtual trades, or any other attributes associated with an Account or stored on our service.</p>`,
    ],
  },
  {
    section: [
      `<h3>Ownership of Creations</h3>`,
      `<br/>`,
      `<p>All content, materials, or strategies created using our AI tools or during the coaching process will be owned exclusively by the Company. Users will not retain any ownership rights to these creations. Content developed using our AI systems, tools, or methodologies will automatically belong to the Company. Additionally, any improvements, derivatives, or innovations generated by AI or collaboratively during the process will be the sole property of the Company, without any reservation.</p>
        <br/>
        <p>By accessing our services, you acknowledge and agree that your contributions to the AI's learning and any improvements arising from this interaction are integral to the Company’s proprietary system and its ownership.</p>`,
    ],
  },
  {
    section: [
      `<h3>Limitations on Use</h3>`,
      `<br/>`,
      `<p>Any use of our services in violation of these above Limitations is strictly prohibited, can result in the immediate revocation of your limited license granted under this Terms, and may subject you to liability for violations of law. Any attempt by you to disrupt or interfere with the service, including undermining or manipulating the legitimate operation interests, is violation of our rights and may be a violation of laws. Users agree not to misuse the AI tools for unethical, unlawful, or malicious purposes. Misuse includes but is not limited to exploiting the AI for fraudulent activities, violating intellectual property laws, or harming others.</p>`,
    ],
  },
  {
    section: [
      `<h3>DISCLAIMER OF WARRANTIES AND LIABILITIES</h3>`,
      `<br/>`,
      `<p>The Website, Services, and content are provided "as-is" and "as-available" without any warranties of any kind, whether express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not represent or warrant that the Services or any content or information on the Website are accurate, complete, reliable, current, or error-free. The functionality of our AI-powered signals and automated trading tools relies on advanced algorithms and machine learning models, but their effectiveness cannot be guaranteed under all market conditions.</p>
        <br/>
        <p>You acknowledge and agree that all Services provided on this Website are for informational and educational purposes only and do not constitute investment or financial advice under any applicable laws or regulations. The data, information, and content related to trading opportunities are provided for general guidance and should not be interpreted as a recommendation or invitation to engage in specific trades or investments.</p>
        <br/>
        <p>Considering the inherent volatility of financial markets, you understand that past performance does not guarantee future results. The use of our AI-powered tools, signals, and strategies involves significant risk, and losses may occur. Any reliance on these tools is solely at your discretion and risk.</p>
        <br/>
        <p>To the fullest extent permitted by law, we disclaim any liability for losses or damages incurred by you or third parties as a result of using the Services, including but not limited to direct, indirect, incidental, consequential, or punitive damages. In the event our liability is determined by a competent authority, it shall be limited to the fees paid by you for the respective Services.</p>
        <p>We are not responsible for interruptions or failures in the provision of Services caused by factors beyond our control, including technical issues or Force Majeure events. Additionally, our employees, representatives, or affiliates are not authorized to provide investment advice or guarantees regarding trading outcomes. No such information should be relied upon as official guidance.</p>
        <br/>
        <p>It is your responsibility to thoroughly evaluate the risks associated with Forex trading and to seek independent financial or legal advice as needed.</p>
        <br/>
        <p>The AI tools provided on this platform are continually evolving. While we strive for accuracy and reliability, the results, recommendations, or outputs generated by our AI systems may not be error-free or entirely accurate. Users are advised to exercise independent judgment and validate all AI-generated outputs before making any decisions.</p>`,
    ],
  },
  {
    section: [
      `<h3>LIMITATION OF LIABILITY</h3>`,
      `<br/>`,
      `<p>To the maximum extent permitted by applicable law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or in connection with the Your use of the Website or the Services. We are not liable for any actions taken based on the recommendations, insights, or predictions made by our AI-powered tools. Users are solely responsible for verifying the outputs and ensuring their appropriateness for the Users’ individual trading strategies.</p>`,
    ],
  },
  {
    section: [
      `<h3>Third Party Content</h3>`,
      `<br/>`,
      `<p>The Services include resources and content provided by third parties or links to third party services (“Third Party Content”). We are not and shall not be liable or responsible for any Third-Party Content and does not control its availability. Should you leave the Services via a link or use Third Party Content, you do so at your own risk. In as much as you are redirected to linked sites, applications and content, We recommend you to carefully read and abide by the terms of use and privacy policies of such applications, sites and content, before proceeding.</p>`,
    ],
  },
  {
    section: [
      `<h3>INDEMNIFICATION</h3>`,
      `<br/>`,
      `<p>You agree to indemnify and hold Company, its subsidiaries and affiliates, and each of their directors, officers, agents, contractors, partners, and employees, harmless from and against any loss, liability, claim, demand, damages, costs and expenses, including actual attorney’s fees, made by any third party due to or arising out of or in connection with any user content or content you post or share on or through the Website, your use of the Service, Premium Service, or the Website, your conduct in connection with the Service or the Website or with other users of the Service or the Website, or any violation of these Terms or of any law or the rights of any third party.</p>`,
    ],
  },
  {
    section: [
      `<h3>COMMUNICATION</h3>`,
      `<br/>`,
      `<p>We will primarily communicate with You regarding the Services through Your account or the email address, through which You have registered with us. For the avoidance of doubt, written electronic communication via email, Live Chat, or through the account is all considered valid communication for the purpose of these terms and conditions.</p>`,
    ],
  },
  {
    section: [
      `<h3>BREACHING THE TERMS</h3>`,
      `<br/>`,
      `<div>
      <p>In the event of any violation, we may take one or more of the following actions, without prior notice and without any compensation to You:</p>
      <ul>
      <li>Prevent You from continuing Subscription.</li>
      <li>Limit or completely restrict Your access to all or some Services, including the user account.</li>
      </ul>
      </div>`,
    ],
  },
  {
    section: [
      `<h3>COMPLAINTS</h3>`,
      `<br/>`,
      `<p>In the event of You experiencing any malfunction or error in our Website or the Platform, You shall notify via email to our Customer Support unit of such malfunction or error in the system, promptly within 12 hours from experiencing the malfunction or the error.</p>
      <br/>
      <p>We shall use our best efforts to resolve any identified materially adverse issues that we become aware of or is notified about, arising on our Website or the Platform without cause or intervention from You, as soon as reasonably practical provided that the You have provided prompt notification to us on the issue within the timelines set out above.</p>
      <br/>
      <p>Without prejudice to the above, We shall not guarantee the resolution of issues caused beyond our control or by actions or inactions by You, Your Representatives or any authorized assignees.</p>`,
    ],
  },
  {
    section: [
      `<h3>CHANGES TO THE TERMS</h3>`,
      `<br/>`,
      `<p>We reserve the right to change these Terms at any time at our discretion, and such changes shall be reflected in the user account. Accordingly, we encourage You to visit our website from time to time stay apprised of any new developments to our terms and conditions.</p>`,
    ],
  },
  {
    section: [
      `<h3>DISPUTE RESOLUTION</h3>`,
      `<br/>`,
      `<h3>Governing Law</h3>`,
      `<br/>`,
      `<p>The terms and any related legal relationships herein are subject to and shall be governed by the laws of Costa Rica. Any disputes arising from these terms or related agreements will be submitted to the exclusive jurisdiction of the courts of Costa Rica.</p>`,
    ],
  },
  {
    section: [
      `<h3>GENERAL PROVISIONS</h3>`,
      `<br/>`,
      `<p>These terms constitute the complete agreement between You and Us and supersede all prior agreements, written or verbal, regarding the subject matter.</p>
        <br/>
        <p>If any provision of these terms is found to be invalid or unenforceable, it will be replaced with a provision that is as close as possible in meaning. The invalidity of one provision will not affect the validity of the remaining provisions.</p>
        <br/>
        <p>No past or future practices or customs established between the parties, or generally observed in the industry, will apply if they are not expressly mentioned in these terms.  These practices and customs cannot be used to interpret the parties' intentions or create rights and obligations.</p>
        <br/>
        <p>Any schedules attached to these terms now in the future are considered integral parts of the agreement.  In the event of any conflict between the main text and a schedule, the terms set out in the main text shall prevail to the extent of the conflict.</p>
        <br/>
        <p>Before accepting these terms, both parties have carefully considered and assessed the potential risks and agree to accept them.</p>
        <br/>
        <p>We may assign any rights, obligations or claims arising from these terms or any agreement (or parts thereof) to a third party without having to obtain Your prior consent.  However, You are not authorized to transfer or assign Your rights and obligations under these terms or any agreements (or parts thereof), or any receivables arising from them to any third party.</p>`,
    ],
  },
];
